apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development

---

apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev
  namespace: development
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-prod
  namespace: prod
  labels:
    app: front-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: front-prod
  template:
    metadata:
      labels:
        app: front-prod
    spec:
      containers:
      - name: nginx
        image: nginx:alpine